"""Strict contract tests for M6 GitHub proposal, approval, and result records."""

from __future__ import annotations

import copy
import hashlib
from dataclasses import replace
from typing import Any, cast

import pytest

from repoguard._canonical import canonical_json_text
from repoguard.agent import FindingSource
from repoguard.github import (
    GITHUB_CHECK_CONFIRMATION,
    GITHUB_REPAIR_CONFIRMATION,
    GitHubApprovalInterface,
    GitHubPermission,
    GitHubProposal,
    GitHubProposalKind,
    GitHubProposalOrigin,
    GitHubPublicationState,
    approve_github_proposal,
    build_github_check_proposal,
    build_github_proposal,
    build_github_repair_proposal,
    build_github_result,
    github_approval_to_json,
    github_proposal_artifact_name,
    github_proposal_from_json,
    github_proposal_to_json,
    github_result_from_json,
    github_result_to_json,
)
from repoguard.product import (
    ProductConclusion,
    ProductFinding,
    ProductReference,
    ProductReviewResult,
)
from repoguard.repair import (
    REPAIR_APPROVAL_CONFIRMATION,
    REPAIR_PUBLICATION_AUTHOR_EMAIL,
    REPAIR_PUBLICATION_AUTHOR_NAME,
    REPAIR_PUBLICATION_COMMIT_MESSAGE,
    RepairApproval,
    RepairCandidate,
    RepairContextOutcome,
    RepairContextSummary,
    RepairPreview,
    RepairPromptIdentity,
    RepairSnapshot,
    RepairState,
    RepairValidation,
    ValidationCommandResult,
)
from repoguard.review import (
    EvidenceSide,
    FindingCategory,
    FindingSeverity,
)

_BASE_OID = "1" * 40
_HEAD_OID = "2" * 40
_CANDIDATE_ID = "3" * 64
_VALIDATION_SHA256 = "4" * 64
_TREE_OID = "5" * 40
_POLICY_SHA256 = "7" * 64
_REVIEW_SHA256 = "8" * 64
_APPLICATION_SHA256 = "9" * 64
_REQUEST_SHA256 = "a" * 64
_SESSION_ID = "b" * 64
_PR_TITLE = "[RepoGuard] Repair candidate 333333333333"
_PR_MARKER = f"<!-- repoguard-repair-candidate:{_CANDIDATE_ID} -->"
_PR_BODY = f"{_PR_MARKER}\nDraft replacement repair generated by RepoGuard."


def _fixed_commit_oid(tree_oid: str = _TREE_OID, head_oid: str = _HEAD_OID) -> str:
    identity = f"{REPAIR_PUBLICATION_AUTHOR_NAME} <{REPAIR_PUBLICATION_AUTHOR_EMAIL}> 0 +0000"
    commit = (
        f"tree {tree_oid}\n"
        f"parent {head_oid}\n"
        f"author {identity}\n"
        f"committer {identity}\n"
        "\n"
        f"{REPAIR_PUBLICATION_COMMIT_MESSAGE}"
    ).encode()
    header = f"commit {len(commit)}\0".encode("ascii")
    return hashlib.sha1(header + commit, usedforsecurity=False).hexdigest()


_COMMIT_OID = _fixed_commit_oid()


def _reference(
    *,
    path: str = "src/app.py",
    side: EvidenceSide = EvidenceSide.NEW,
    start_line: int | None = 7,
    end_line: int | None = 7,
    target: str | None = "c" * 64,
) -> ProductReference:
    return ProductReference(path, side, _HEAD_OID, start_line, end_line, target)


def _finding(
    *,
    severity: FindingSeverity = FindingSeverity.HIGH,
    title: str = "Unsafe change",
    message: str = "Review this exact line.",
    remediation: str = "Use the safe API.",
    references: tuple[ProductReference, ...] | None = None,
    source: FindingSource = FindingSource.DETERMINISTIC,
) -> ProductFinding:
    return ProductFinding(
        source=source,
        rule_id="agent_reasoning" if source is FindingSource.AGENT else "private_key_material",
        category=FindingCategory.SECURITY,
        severity=severity,
        title=title,
        message=message,
        remediation=remediation,
        references=references
        or (_reference(target=None if source is FindingSource.AGENT else "c" * 64),),
    )


def _review(
    *,
    findings: tuple[ProductFinding, ...] = (),
    base_ref: str = "main",
    head_oid: str = _HEAD_OID,
    review_sha256: str = _REVIEW_SHA256,
) -> ProductReviewResult:
    severity_order = {
        FindingSeverity.INFO: 0,
        FindingSeverity.LOW: 1,
        FindingSeverity.MEDIUM: 2,
        FindingSeverity.HIGH: 3,
        FindingSeverity.CRITICAL: 4,
    }
    highest = (
        None
        if not findings
        else max((finding.severity for finding in findings), key=severity_order.__getitem__)
    )
    conclusion = (
        ProductConclusion.FAILURE
        if highest in {FindingSeverity.HIGH, FindingSeverity.CRITICAL}
        else ProductConclusion.SUCCESS
    )
    return ProductReviewResult(
        schema_version=1,
        repository_alias="repository",
        object_format="sha1",
        base_ref=base_ref,
        head_ref="feature",
        base_oid=_BASE_OID,
        head_oid=head_oid,
        merge_base_oid=_BASE_OID,
        review_profile="deterministic",
        provider=None,
        model=None,
        evidence_sha256="d" * 64,
        deterministic_review_sha256="e" * 64,
        review_sha256=review_sha256,
        findings=findings,
        finding_count=len(findings),
        highest_severity=highest,
        conclusion=conclusion,
    )


def _validated_repair(
    *,
    commit_oid: str = _COMMIT_OID,
) -> tuple[RepairSnapshot, RepairPreview]:
    prompt = RepairPromptIdentity(
        "repoguard_repair",
        1,
        "1" * 64,
        "2" * 64,
        "3" * 64,
    )
    context = RepairContextSummary(
        RepairContextOutcome.NOT_REQUESTED,
        None,
        None,
        0,
        0,
        0,
        None,
        None,
    )
    candidate = RepairCandidate(
        1,
        _CANDIDATE_ID,
        _REQUEST_SHA256,
        prompt,
        context,
        "4" * 64,
        _TREE_OID,
        commit_oid,
        ("src/app.py",),
        1,
        0,
        0,
        0,
    )
    command = ValidationCommandResult(
        0,
        0,
        None,
        False,
        1,
        "5" * 64,
        0,
        False,
        "6" * 64,
        0,
        False,
    )
    validation = RepairValidation(
        1,
        _VALIDATION_SHA256,
        _CANDIDATE_ID,
        "7" * 64,
        "8" * 64,
        f"sha256:{'9' * 64}",
        1,
        2,
        True,
        None,
        (command,),
        1,
        False,
        0,
        1,
        1,
        True,
    )
    snapshot = RepairSnapshot(
        1,
        _SESSION_ID,
        RepairState.VALIDATED,
        _REQUEST_SHA256,
        1,
        2,
        1,
        ("src/app.py",),
        candidate,
        validation,
        None,
        None,
        None,
        None,
        False,
    )
    preview = RepairPreview(
        1,
        _SESSION_ID,
        RepairState.VALIDATED,
        _CANDIDATE_ID,
        _VALIDATION_SHA256,
        ("src/app.py",),
        "diff --git a/src/app.py b/src/app.py\n",
        REPAIR_APPROVAL_CONFIRMATION,
    )
    return snapshot, preview


def _check_proposal(
    *,
    review: ProductReviewResult | None = None,
    repository_id: int = 123456,
    repository_full_name: str = "owner/repository",
    policy_sha256: str = _POLICY_SHA256,
) -> GitHubProposal:
    return build_github_check_proposal(
        repository_id=repository_id,
        repository_full_name=repository_full_name,
        pull_request_number=7,
        base_ref="main",
        origin=GitHubProposalOrigin.CLI,
        review_result=_review() if review is None else review,
        policy_sha256=policy_sha256,
        created_at_us=1_000_000,
    )


def _repair_proposal(
    *,
    review: ProductReviewResult | None = None,
    snapshot: RepairSnapshot | None = None,
    preview: RepairPreview | None = None,
) -> GitHubProposal:
    default_snapshot, default_preview = _validated_repair()
    return build_github_repair_proposal(
        repository_id=123456,
        repository_full_name="owner/repository",
        pull_request_number=7,
        base_ref="main",
        origin=GitHubProposalOrigin.CLI,
        review_result=_review() if review is None else review,
        profile_name="safe",
        snapshot=default_snapshot if snapshot is None else snapshot,
        preview=default_preview if preview is None else preview,
        created_at_us=1_000_000,
    )


def _check_payload() -> dict[str, object]:
    return cast(dict[str, object], _check_proposal().payload)


def _repair_payload() -> dict[str, object]:
    return cast(dict[str, object], _repair_proposal().payload)


def _proposal(kind: GitHubProposalKind = GitHubProposalKind.CHECK) -> GitHubProposal:
    return _check_proposal() if kind is GitHubProposalKind.CHECK else _repair_proposal()


def test_check_proposal_round_trip_is_canonical_and_has_fixed_artifact_name() -> None:
    proposal = _proposal()

    encoded = github_proposal_to_json(proposal)

    assert github_proposal_from_json(encoded.encode("utf-8")) == proposal
    assert not encoded.endswith("\n")
    assert github_proposal_artifact_name(proposal) == (
        f"repoguard-proposal-v1-{proposal.proposal_sha256}"
    )
    assert proposal.expires_at_us - proposal.created_at_us == 86_400_000_000


def test_proposal_base_branch_is_distinct_from_exact_review_base_revision() -> None:
    review = _review(base_ref=_BASE_OID)

    proposal = build_github_check_proposal(
        repository_id=123456,
        repository_full_name="owner/repository",
        pull_request_number=7,
        base_ref="main",
        origin=GitHubProposalOrigin.CLI,
        review_result=review,
        policy_sha256=_POLICY_SHA256,
        created_at_us=1_000_000,
    )

    assert review.base_ref == _BASE_OID
    assert proposal.base_ref == "main"
    assert proposal.base_oid == _BASE_OID


def test_check_builder_derives_plain_text_summary_and_stable_annotations() -> None:
    critical = _finding(
        severity=FindingSeverity.CRITICAL,
        title="@octocat <details> [click](https://evil.invalid) `code` " + "[" * 300,
        message="# heading **bold** @team",
        remediation="Never run <script>.",
        references=(_reference(path="z.py", start_line=9, end_line=10, target=None),),
        source=FindingSource.AGENT,
    )
    high = _finding(
        severity=FindingSeverity.HIGH,
        references=(_reference(path="a.py", start_line=1, end_line=1, target=None),),
        source=FindingSource.AGENT,
    )
    medium = _finding(
        severity=FindingSeverity.MEDIUM,
        references=(_reference(path="b.py", start_line=2, end_line=2, target=None),),
        source=FindingSource.AGENT,
    )
    old_only = _finding(
        severity=FindingSeverity.CRITICAL,
        references=(
            _reference(
                path="old.py",
                side=EvidenceSide.OLD,
                start_line=3,
                end_line=3,
                target=None,
            ),
        ),
        source=FindingSource.AGENT,
    )
    proposal = _check_proposal(review=_review(findings=(high, medium, critical, old_only)))
    payload = proposal.payload
    annotations = cast(list[dict[str, object]], payload["annotations"])

    assert [annotation["path"] for annotation in annotations] == ["z.py", "a.py", "b.py"]
    assert [annotation["annotation_level"] for annotation in annotations] == [
        "failure",
        "failure",
        "warning",
    ]
    assert payload["summary"] == (
        "RepoGuard review\n"
        "Conclusion: failure\n"
        "Findings: 4\n"
        "Highest severity: critical\n"
        "Annotations: 3\n"
        "Omitted annotations: 1"
    )
    rendered = "\n".join(
        f"{annotation['title']}\n{annotation['message']}" for annotation in annotations
    )
    assert all(token not in rendered for token in ("@", "<", ">", "[", "]", "`", "*"))
    assert "&#64;" not in rendered
    assert "\uff20octocat" in rendered
    assert len(cast(str, annotations[0]["title"]).encode("utf-8")) <= 255
    assert cast(str, annotations[0]["title"]).endswith("&#8230;")
    assert "octocat" in rendered


def test_check_builder_caps_annotations_and_reports_exact_omitted_count() -> None:
    references = tuple(
        _reference(
            path="src/generated.py",
            start_line=line,
            end_line=line,
            target=None,
        )
        for line in range(1, 1_002)
    )
    finding = _finding(
        severity=FindingSeverity.LOW,
        references=references,
        source=FindingSource.AGENT,
    )

    proposal = _check_proposal(review=_review(findings=(finding,)))
    payload = proposal.payload
    annotations = cast(list[dict[str, object]], payload["annotations"])

    assert len(annotations) == 1_000
    assert annotations[0]["start_line"] == 1
    assert annotations[-1]["start_line"] == 1_000
    assert payload["omitted_count"] == 1
    assert cast(str, payload["summary"]).endswith("Omitted annotations: 1")


def test_check_external_id_binds_repository_head_review_and_policy() -> None:
    original = _check_proposal()
    changed_repository_id = _check_proposal(repository_id=654321)
    changed_repository_name = _check_proposal(repository_full_name="owner/other")
    changed_head = _check_proposal(review=_review(head_oid="f" * 40, review_sha256="1" * 64))
    changed_review = _check_proposal(review=_review(review_sha256="2" * 64))
    changed_policy = _check_proposal(policy_sha256="3" * 64)
    external_ids = {
        cast(str, proposal.payload["external_id"])
        for proposal in (
            original,
            changed_repository_id,
            changed_repository_name,
            changed_head,
            changed_review,
            changed_policy,
        )
    }

    assert _check_proposal() == original
    assert len(external_ids) == 6


@pytest.mark.parametrize(
    ("field", "replacement"),
    [
        ("external_id", "f" * 64),
        ("summary", "spoofed"),
        ("omitted_count", 1),
        ("annotations", []),
    ],
)
def test_check_payload_rejects_any_derived_field_mismatch(
    field: str,
    replacement: object,
) -> None:
    payload = cast(
        dict[str, object],
        copy.deepcopy(_check_proposal(review=_review(findings=(_finding(),))).payload),
    )
    payload[field] = replacement

    with pytest.raises(ValueError, match="check"):
        build_github_proposal(
            kind=GitHubProposalKind.CHECK,
            repository_id=123456,
            repository_full_name="owner/repository",
            pull_request_number=7,
            base_ref="main",
            base_oid=_BASE_OID,
            head_oid=_HEAD_OID,
            origin=GitHubProposalOrigin.CLI,
            profile_name="deterministic",
            payload=payload,
            created_at_us=1_000_000,
        )


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("repository_id", 654321),
        ("repository_full_name", "owner/other"),
        ("pull_request_number", 8),
        ("base_ref", "release"),
        ("base_oid", "a" * 40),
        ("head_oid", "b" * 40),
        ("origin", GitHubProposalOrigin.MCP),
        ("profile_name", "other"),
        ("created_at_us", 2_000_000),
        ("expires_at_us", 86_402_000_000),
        (
            "payload_json",
            canonical_json_text({**_check_payload(), "summary": "changed"}),
        ),
    ],
)
def test_every_proposal_cas_field_invalidates_its_digest(field: str, value: object) -> None:
    proposal = _proposal()

    with pytest.raises(ValueError):
        replace(proposal, **cast(dict[str, Any], {field: value}))


def test_approval_requires_unexpired_proposal_permission_and_exact_confirmation() -> None:
    proposal = _proposal()
    approval = approve_github_proposal(
        proposal,
        actor_login="reviewer",
        actor_id=42,
        permission=GitHubPermission.MAINTAIN,
        interface=GitHubApprovalInterface.CLI,
        confirmation=GITHUB_CHECK_CONFIRMATION,
        approved_at_us=2_000_000,
    )

    assert approval.proposal_sha256 == proposal.proposal_sha256
    assert "reviewer" in github_approval_to_json(approval)
    with pytest.raises(ValueError, match="confirmation"):
        approve_github_proposal(
            proposal,
            actor_login="reviewer",
            actor_id=42,
            permission=GitHubPermission.WRITE,
            interface=GitHubApprovalInterface.MCP,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
            approved_at_us=2_000_000,
        )
    with pytest.raises(ValueError, match="expired"):
        approve_github_proposal(
            proposal,
            actor_login="reviewer",
            actor_id=42,
            permission=GitHubPermission.ADMIN,
            interface=GitHubApprovalInterface.ACTION,
            confirmation=GITHUB_CHECK_CONFIRMATION,
            approved_at_us=proposal.expires_at_us,
        )


def test_result_binds_complete_approval_application_and_readback() -> None:
    proposal = _proposal(GitHubProposalKind.REPAIR)
    approval = approve_github_proposal(
        proposal,
        actor_login="maintainer",
        actor_id=99,
        permission=GitHubPermission.ADMIN,
        interface=GitHubApprovalInterface.ACTION,
        confirmation=GITHUB_REPAIR_CONFIRMATION,
        approved_at_us=2_000_000,
    )
    readback = {
        "repository_id": 123456,
        "branch_ref": f"refs/heads/repoguard/repairs/{_CANDIDATE_ID}",
        "commit_oid": _COMMIT_OID,
        "pull_request_id": 555,
        "pull_request_number": 8,
        "pull_request_node_id": "PR_node",
        "pull_request_url": "https://github.com/owner/repository/pull/8",
        "draft": True,
        "state": "open",
        "base_ref": "main",
        "head_ref": f"repoguard/repairs/{_CANDIDATE_ID}",
        "base_repository_id": 123456,
        "head_repository_id": 123456,
        "pull_request_title": _PR_TITLE,
        "pull_request_body": _PR_BODY,
        "body_marker": _PR_MARKER,
    }

    result = build_github_result(
        proposal,
        approval,
        state=GitHubPublicationState.REPAIR_PUBLISHED,
        application_sha256=_APPLICATION_SHA256,
        readback=readback,
        published_at_us=3_000_000,
    )

    encoded = github_result_to_json(result)
    assert github_result_from_json(encoded.encode("utf-8"), proposal=proposal) == result
    assert approval.approval_sha256 in encoded
    assert _APPLICATION_SHA256 in encoded
    assert _COMMIT_OID in encoded
    with pytest.raises(ValueError, match="result identity"):
        replace(
            result,
            readback_json=canonical_json_text({**readback, "pull_request_number": 9}),
        )


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("repository_id", 654321),
        ("branch_ref", f"refs/heads/repoguard/repairs/{'e' * 64}"),
        ("commit_oid", "f" * 40),
        ("pull_request_url", "https://github.com/attacker/other/pull/8"),
        ("base_ref", "release"),
        ("head_repository_id", 999999),
        ("pull_request_title", "[RepoGuard] Different repair"),
        ("pull_request_body", f"{_PR_MARKER}\nDifferent body."),
    ],
)
def test_repair_result_rejects_readback_not_authorized_by_proposal(
    field: str,
    value: object,
) -> None:
    proposal = _proposal(GitHubProposalKind.REPAIR)
    approval = approve_github_proposal(
        proposal,
        actor_login="maintainer",
        actor_id=99,
        permission=GitHubPermission.ADMIN,
        interface=GitHubApprovalInterface.CLI,
        confirmation=GITHUB_REPAIR_CONFIRMATION,
        approved_at_us=2_000_000,
    )
    readback = {
        "repository_id": 123456,
        "branch_ref": f"refs/heads/repoguard/repairs/{_CANDIDATE_ID}",
        "commit_oid": _COMMIT_OID,
        "pull_request_id": 555,
        "pull_request_number": 8,
        "pull_request_node_id": "PR_node",
        "pull_request_url": "https://github.com/owner/repository/pull/8",
        "draft": True,
        "state": "open",
        "base_ref": "main",
        "head_ref": f"repoguard/repairs/{_CANDIDATE_ID}",
        "base_repository_id": 123456,
        "head_repository_id": 123456,
        "pull_request_title": _PR_TITLE,
        "pull_request_body": _PR_BODY,
        "body_marker": _PR_MARKER,
    }
    readback[field] = value

    with pytest.raises(ValueError, match="proposal"):
        build_github_result(
            proposal,
            approval,
            state=GitHubPublicationState.REPAIR_PUBLISHED,
            application_sha256=_APPLICATION_SHA256,
            readback=readback,
            published_at_us=3_000_000,
        )


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("repository_id", 654321),
        ("head_oid", "f" * 40),
        ("external_id", "e" * 64),
        ("conclusion", "failure"),
        ("check_run_url", "https://github.com/attacker/other/runs/17"),
    ],
)
def test_check_result_rejects_readback_not_authorized_by_proposal(
    field: str,
    value: object,
) -> None:
    proposal = _proposal()
    approval = approve_github_proposal(
        proposal,
        actor_login="maintainer",
        actor_id=99,
        permission=GitHubPermission.WRITE,
        interface=GitHubApprovalInterface.MCP,
        confirmation=GITHUB_CHECK_CONFIRMATION,
        approved_at_us=2_000_000,
    )
    readback = {
        "repository_id": 123456,
        "check_run_id": 17,
        "check_run_node_id": "CR_node",
        "head_oid": _HEAD_OID,
        "external_id": cast(str, proposal.payload["external_id"]),
        "status": "completed",
        "conclusion": "success",
        "check_run_url": "https://github.com/owner/repository/runs/17",
    }
    readback[field] = value

    with pytest.raises(ValueError, match="proposal"):
        build_github_result(
            proposal,
            approval,
            state=GitHubPublicationState.CHECK_PUBLISHED,
            application_sha256=None,
            readback=readback,
            published_at_us=3_000_000,
        )


def test_repair_proposal_is_session_free_and_rejects_unknown_payload_fields() -> None:
    proposal = _proposal(GitHubProposalKind.REPAIR)
    encoded = github_proposal_to_json(proposal)

    assert '"session_id"' not in encoded
    assert proposal.payload["repository_alias"] == "repository"
    assert proposal.payload["tree_oid"] == _TREE_OID
    assert proposal.payload["commit_oid"] == _COMMIT_OID
    assert proposal.payload["pull_request_title"] == _PR_TITLE
    assert proposal.payload["pull_request_body"] == _PR_BODY
    payload = _repair_payload()
    payload["session_id"] = "f" * 64
    with pytest.raises(ValueError, match="repair proposal payload"):
        build_github_proposal(
            kind=GitHubProposalKind.REPAIR,
            repository_id=123456,
            repository_full_name="owner/repository",
            pull_request_number=7,
            base_ref="main",
            base_oid=_BASE_OID,
            head_oid=_HEAD_OID,
            origin=GitHubProposalOrigin.ACTION,
            profile_name="safe",
            payload=payload,
            created_at_us=1_000_000,
        )


@pytest.mark.parametrize(
    "mismatch",
    [
        "snapshot_state",
        "session",
        "candidate",
        "validation",
        "paths",
        "allowlist",
        "local_approval",
        "commit",
        "head",
    ],
)
def test_repair_builder_rejects_m5_identity_mismatches(mismatch: str) -> None:
    snapshot, preview = _validated_repair()
    review = _review()
    if mismatch == "snapshot_state":
        snapshot = replace(snapshot, state=RepairState.VALIDATING)
    elif mismatch == "session":
        preview = replace(preview, session_id="d" * 64)
    elif mismatch == "candidate":
        preview = replace(preview, candidate_id="d" * 64)
    elif mismatch == "validation":
        preview = replace(preview, validation_sha256="d" * 64)
    elif mismatch == "paths":
        preview = replace(preview, changed_paths=("other.py",))
    elif mismatch == "allowlist":
        snapshot = replace(snapshot, allowed_paths=("other.py",))
    elif mismatch == "local_approval":
        snapshot = replace(
            snapshot,
            approval=RepairApproval(
                1,
                "d" * 64,
                _CANDIDATE_ID,
                _VALIDATION_SHA256,
                "uid:1000",
                REPAIR_APPROVAL_CONFIRMATION,
                3,
            ),
        )
    elif mismatch == "commit":
        assert snapshot.candidate is not None
        snapshot = replace(
            snapshot,
            candidate=replace(snapshot.candidate, commit_oid="f" * 40),
        )
    else:
        review = _review(head_oid="f" * 40, review_sha256="1" * 64)

    with pytest.raises(ValueError, match="repair proposal"):
        _repair_proposal(review=review, snapshot=snapshot, preview=preview)


def test_repair_builder_rejects_non_sha1_review() -> None:
    review = replace(
        _review(),
        object_format="sha256",
        base_oid="1" * 64,
        head_oid="2" * 64,
        merge_base_oid="1" * 64,
    )

    with pytest.raises(ValueError, match="SHA-1"):
        _repair_proposal(review=review)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("tree_oid", "f" * 40),
        ("commit_oid", "f" * 40),
        (
            "pull_request_body",
            f"{_PR_MARKER}\n@attacker",
        ),
    ],
)
def test_repair_payload_rejects_commit_head_or_fixed_body_mismatch(
    field: str,
    value: object,
) -> None:
    payload = _repair_payload()
    payload[field] = value

    with pytest.raises(ValueError, match="repair proposal"):
        build_github_proposal(
            kind=GitHubProposalKind.REPAIR,
            repository_id=123456,
            repository_full_name="owner/repository",
            pull_request_number=7,
            base_ref="main",
            base_oid=_BASE_OID,
            head_oid=_HEAD_OID,
            origin=GitHubProposalOrigin.ACTION,
            profile_name="safe",
            payload=payload,
            created_at_us=1_000_000,
        )


def test_check_proposal_requires_complete_review_and_exact_revisions() -> None:
    payload = _check_payload()
    review = cast(dict[str, object], payload["review_result"])
    review["unknown"] = True
    with pytest.raises(ValueError, match="product review result"):
        build_github_proposal(
            kind=GitHubProposalKind.CHECK,
            repository_id=123456,
            repository_full_name="owner/repository",
            pull_request_number=7,
            base_ref="main",
            base_oid=_BASE_OID,
            head_oid=_HEAD_OID,
            origin=GitHubProposalOrigin.CLI,
            profile_name="deterministic",
            payload=payload,
            created_at_us=1_000_000,
        )

    payload = _check_payload()
    review = cast(dict[str, object], payload["review_result"])
    review["head_oid"] = "f" * 40
    with pytest.raises(ValueError, match="revisions"):
        build_github_proposal(
            kind=GitHubProposalKind.CHECK,
            repository_id=123456,
            repository_full_name="owner/repository",
            pull_request_number=7,
            base_ref="main",
            base_oid=_BASE_OID,
            head_oid=_HEAD_OID,
            origin=GitHubProposalOrigin.CLI,
            profile_name="deterministic",
            payload=payload,
            created_at_us=1_000_000,
        )
