"""Approval, read-back, and recovery tests for the M6 GitHub writer."""

from __future__ import annotations

import base64
import hashlib
import json
from dataclasses import replace
from pathlib import Path
from typing import cast

import pytest

from repoguard._github_store import GitHubPublicationStore
from repoguard.agent import FindingSource
from repoguard.github import (
    GITHUB_CHECK_CONFIRMATION,
    GITHUB_REPAIR_CONFIRMATION,
    GitHubApprovalInterface,
    GitHubProposal,
    GitHubProposalOrigin,
    GitHubPublicationState,
    build_github_check_proposal,
    build_github_repair_proposal,
)
from repoguard.github_publication import (
    GitHubPublicationError,
    GitHubPublicationErrorCode,
    GitHubPublicationErrorDomain,
    GitHubPublicationService,
    GitHubPublicationStage,
)
from repoguard.github_transport import (
    GitHubTransport,
    GitHubWireRequest,
    GitHubWireResponse,
)
from repoguard.product import (
    ProductConclusion,
    ProductFinding,
    ProductReference,
    ProductReviewResult,
)
from repoguard.repair import (
    REPAIR_APPROVAL_CONFIRMATION,
    REPAIR_PUBLICATION_AUTHOR_EMAIL,
    REPAIR_PUBLICATION_AUTHOR_NAME,
    REPAIR_PUBLICATION_COMMIT_MESSAGE,
    RepairApplication,
    RepairApproval,
    RepairCandidate,
    RepairContextOutcome,
    RepairContextSummary,
    RepairPreview,
    RepairPromptIdentity,
    RepairPublicationBlob,
    RepairPublicationEntry,
    RepairPublicationManifest,
    RepairSnapshot,
    RepairState,
    RepairValidation,
    ValidationCommandResult,
)
from repoguard.review import EvidenceSide, FindingCategory, FindingSeverity

_BASE_OID = "1" * 40
_HEAD_OID = "2" * 40
_PARENT_TREE_OID = "3" * 40
_TREE_OID = "4" * 40
_CANDIDATE_ID = "5" * 64
_VALIDATION_SHA256 = "6" * 64
_SESSION_ID = "7" * 64
_APPLICATION_SHA256 = "8" * 64
_LOCAL_APPROVAL_SHA256 = "9" * 64
_REPOSITORY_ID = 123456
_REPOSITORY_FULL_NAME = "owner/repository"
_BRANCH = f"repoguard/repairs/{_CANDIDATE_ID}"
_BRANCH_REF = f"refs/heads/{_BRANCH}"
_MARKER = f"<!-- repoguard-repair-candidate:{_CANDIDATE_ID} -->"
_PR_TITLE = f"[RepoGuard] Repair candidate {_CANDIDATE_ID[:12]}"
_PR_BODY = f"{_MARKER}\nDraft replacement repair generated by RepoGuard."
_BLOB_CONTENT = b"safe repair\n"


def _git_blob_oid(content: bytes) -> str:
    header = f"blob {len(content)}\0".encode("ascii")
    return hashlib.sha1(header + content, usedforsecurity=False).hexdigest()


_BLOB_OID = _git_blob_oid(_BLOB_CONTENT)


def _fixed_commit_oid() -> str:
    identity = f"{REPAIR_PUBLICATION_AUTHOR_NAME} <{REPAIR_PUBLICATION_AUTHOR_EMAIL}> 0 +0000"
    content = (
        f"tree {_TREE_OID}\n"
        f"parent {_HEAD_OID}\n"
        f"author {identity}\n"
        f"committer {identity}\n"
        "\n"
        f"{REPAIR_PUBLICATION_COMMIT_MESSAGE}"
    ).encode()
    header = f"commit {len(content)}\0".encode("ascii")
    return hashlib.sha1(header + content, usedforsecurity=False).hexdigest()


_COMMIT_OID = _fixed_commit_oid()


def _review(*, annotation_count: int = 0) -> ProductReviewResult:
    findings: tuple[ProductFinding, ...] = ()
    if annotation_count:
        references = tuple(
            ProductReference(
                path="src/app.py",
                side=EvidenceSide.NEW,
                oid=_HEAD_OID,
                start_line=line,
                end_line=line,
                repair_target_id=None,
            )
            for line in range(1, annotation_count + 1)
        )
        findings = (
            ProductFinding(
                source=FindingSource.AGENT,
                rule_id="agent_reasoning",
                category=FindingCategory.SECURITY,
                severity=FindingSeverity.LOW,
                title="Review finding",
                message="Review this line.",
                remediation="Keep the safe behavior.",
                references=references,
            ),
        )
    return ProductReviewResult(
        schema_version=1,
        repository_alias="repository",
        object_format="sha1",
        base_ref="base-input",
        head_ref="head-input",
        base_oid=_BASE_OID,
        head_oid=_HEAD_OID,
        merge_base_oid=_BASE_OID,
        review_profile="deterministic",
        provider=None,
        model=None,
        evidence_sha256="a" * 64,
        deterministic_review_sha256="b" * 64,
        review_sha256="c" * 64,
        findings=findings,
        finding_count=len(findings),
        highest_severity=None if not findings else FindingSeverity.LOW,
        conclusion=ProductConclusion.SUCCESS,
    )


def _validated_repair() -> tuple[RepairSnapshot, RepairPreview]:
    prompt = RepairPromptIdentity("repoguard_repair", 1, "1" * 64, "2" * 64, "3" * 64)
    context = RepairContextSummary(
        RepairContextOutcome.NOT_REQUESTED,
        None,
        None,
        0,
        0,
        0,
        None,
        None,
    )
    candidate = RepairCandidate(
        1,
        _CANDIDATE_ID,
        "d" * 64,
        prompt,
        context,
        "e" * 64,
        _TREE_OID,
        _COMMIT_OID,
        ("src/app.py",),
        1,
        0,
        0,
        0,
    )
    command = ValidationCommandResult(
        0,
        0,
        None,
        False,
        1,
        "f" * 64,
        0,
        False,
        "0" * 64,
        0,
        False,
    )
    validation = RepairValidation(
        1,
        _VALIDATION_SHA256,
        _CANDIDATE_ID,
        "1" * 64,
        "2" * 64,
        f"sha256:{'3' * 64}",
        1,
        2,
        True,
        None,
        (command,),
        1,
        False,
        0,
        1,
        1,
        True,
    )
    snapshot = RepairSnapshot(
        1,
        _SESSION_ID,
        RepairState.VALIDATED,
        "d" * 64,
        1,
        2,
        1,
        ("src/app.py",),
        candidate,
        validation,
        None,
        None,
        None,
        None,
        False,
    )
    preview = RepairPreview(
        1,
        _SESSION_ID,
        RepairState.VALIDATED,
        _CANDIDATE_ID,
        _VALIDATION_SHA256,
        ("src/app.py",),
        "diff --git a/src/app.py b/src/app.py\n",
        REPAIR_APPROVAL_CONFIRMATION,
    )
    return snapshot, preview


def _check_proposal(*, annotations: int = 0) -> GitHubProposal:
    return build_github_check_proposal(
        repository_id=_REPOSITORY_ID,
        repository_full_name=_REPOSITORY_FULL_NAME,
        pull_request_number=7,
        base_ref="main",
        origin=GitHubProposalOrigin.CLI,
        review_result=_review(annotation_count=annotations),
        policy_sha256="d" * 64,
        created_at_us=1_000_000,
    )


def _repair_proposal() -> GitHubProposal:
    snapshot, preview = _validated_repair()
    return build_github_repair_proposal(
        repository_id=_REPOSITORY_ID,
        repository_full_name=_REPOSITORY_FULL_NAME,
        pull_request_number=7,
        base_ref="main",
        origin=GitHubProposalOrigin.CLI,
        review_result=_review(),
        profile_name="safe",
        snapshot=snapshot,
        preview=preview,
        created_at_us=1_000_000,
    )


@pytest.fixture
def state_root(tmp_path: Path) -> Path:
    root = tmp_path / "product-state"
    root.mkdir(mode=0o700)
    return root


def _store(root: Path) -> GitHubPublicationStore:
    return GitHubPublicationStore(
        product_state_root=root,
        repository_alias="repository",
        repository_id=_REPOSITORY_ID,
        repository_full_name=_REPOSITORY_FULL_NAME,
    )


def _json_response(status: int, value: object) -> GitHubWireResponse:
    return GitHubWireResponse(
        status=status,
        headers=(("Content-Type", "application/json"),),
        body=json.dumps(value, separators=(",", ":")).encode(),
    )


class _FakeGitHub:
    def __init__(self) -> None:
        self.actor_id = 42
        self.actor_login = "reviewer"
        self.permission = "write"
        self.repository_is_fork = False
        self.source_state = "open"
        self.source_head_oid = _HEAD_OID
        self.requests: list[GitHubWireRequest] = []
        self.check: dict[str, object] | None = None
        self.check_annotations: list[dict[str, object]] = []
        self.ambiguous_check_create = False
        self.ambiguous_check_append = False
        self.ambiguous_check_final = False
        self.blobs: set[str] = set()
        self.tree_exists = False
        self.commit_exists = False
        self.ambiguous_blob = False
        self.ambiguous_tree = False
        self.ambiguous_commit = False
        self.ambiguous_branch = False
        self.ambiguous_pull_request = False
        self.branch_oid: str | None = None
        self.replacement: dict[str, object] | None = None
        self.fail_pull_request = False

    @property
    def write_requests(self) -> list[GitHubWireRequest]:
        return [item for item in self.requests if item.method.value in {"POST", "PATCH"}]

    def send(self, request: GitHubWireRequest) -> GitHubWireResponse:
        self.requests.append(request)
        target = request.target
        body = (
            {}
            if request.body is None
            else cast(dict[str, object], json.loads(request.body.decode()))
        )
        if request.method.value == "GET" and target == "/user":
            return _json_response(
                200,
                {"id": self.actor_id, "login": self.actor_login},
            )
        if target == (f"/repos/owner/repository/collaborators/{self.actor_login}/permission"):
            return _json_response(
                200,
                {
                    "permission": self.permission,
                    "user": {"id": self.actor_id, "login": self.actor_login},
                },
            )
        if target == "/repos/owner/repository":
            return _json_response(
                200,
                {
                    "id": _REPOSITORY_ID,
                    "full_name": _REPOSITORY_FULL_NAME,
                    "fork": self.repository_is_fork,
                },
            )
        if target == "/repos/owner/repository/pulls/7":
            return _json_response(200, self._source_pull_request())
        if "/commits/" in target and "/check-runs?" in target:
            values = [] if self.check is None else [self.check]
            return _json_response(200, {"total_count": len(values), "check_runs": values})
        if request.method.value == "POST" and target.endswith("/check-runs"):
            self.check_annotations.extend(
                cast(
                    list[dict[str, object]],
                    cast(dict[str, object], body["output"])["annotations"],
                )
            )
            self.check = self._check_run(
                external_id=cast(str, body["external_id"]),
                status="in_progress",
                conclusion=None,
                summary=cast(str, cast(dict[str, object], body["output"])["summary"]),
            )
            if self.ambiguous_check_create:
                self.ambiguous_check_create = False
                raise TimeoutError
            return _json_response(201, self.check)
        if "/check-runs/17/annotations?" in target:
            query = target.split("?", 1)[1]
            page = int(query.rsplit("=", 1)[1])
            start = (page - 1) * 100
            return _json_response(200, self.check_annotations[start : start + 100])
        if target.endswith("/check-runs/17") and request.method.value == "GET":
            assert self.check is not None
            return _json_response(200, self.check)
        if target.endswith("/check-runs/17") and request.method.value == "PATCH":
            assert self.check is not None
            output = cast(dict[str, object], body["output"])
            annotations = cast(list[dict[str, object]], output.get("annotations", []))
            self.check_annotations.extend(annotations)
            status = cast(str, body["status"])
            conclusion = cast(str | None, body.get("conclusion"))
            self.check = self._check_run(
                external_id=cast(str, self.check["external_id"]),
                status=status,
                conclusion=conclusion,
                summary=cast(str, output["summary"]),
            )
            if status == "in_progress" and self.ambiguous_check_append:
                self.ambiguous_check_append = False
                raise TimeoutError
            if status == "completed" and self.ambiguous_check_final:
                self.ambiguous_check_final = False
                raise TimeoutError
            return _json_response(200, self.check)
        if target == f"/repos/owner/repository/git/commits/{_HEAD_OID}":
            return _json_response(
                200,
                {"sha": _HEAD_OID, "tree": {"sha": _PARENT_TREE_OID}, "parents": []},
            )
        if target == f"/repos/owner/repository/git/blobs/{_BLOB_OID}":
            if _BLOB_OID not in self.blobs:
                return _json_response(404, {"message": "not found"})
            return _json_response(
                200,
                {
                    "sha": _BLOB_OID,
                    "size": len(_BLOB_CONTENT),
                    "encoding": "base64",
                    "content": base64.b64encode(_BLOB_CONTENT).decode(),
                },
            )
        if request.method.value == "POST" and target.endswith("/git/blobs"):
            content = base64.b64decode(cast(str, body["content"]), validate=True)
            oid = _git_blob_oid(content)
            self.blobs.add(oid)
            if self.ambiguous_blob:
                self.ambiguous_blob = False
                raise TimeoutError
            return _json_response(201, {"sha": oid})
        if target == f"/repos/owner/repository/git/trees/{_TREE_OID}":
            if not self.tree_exists:
                return _json_response(404, {"message": "not found"})
            return _json_response(200, {"sha": _TREE_OID})
        if request.method.value == "POST" and target.endswith("/git/trees"):
            assert body["base_tree"] == _PARENT_TREE_OID
            self.tree_exists = True
            if self.ambiguous_tree:
                self.ambiguous_tree = False
                raise TimeoutError
            return _json_response(201, {"sha": _TREE_OID})
        if target == f"/repos/owner/repository/git/commits/{_COMMIT_OID}":
            if not self.commit_exists:
                return _json_response(404, {"message": "not found"})
            return _json_response(
                200,
                {
                    "sha": _COMMIT_OID,
                    "tree": {"sha": _TREE_OID},
                    "parents": [{"sha": _HEAD_OID}],
                },
            )
        if request.method.value == "POST" and target.endswith("/git/commits"):
            assert body["tree"] == _TREE_OID
            assert body["parents"] == [_HEAD_OID]
            self.commit_exists = True
            if self.ambiguous_commit:
                self.ambiguous_commit = False
                raise TimeoutError
            return _json_response(
                201,
                {"sha": _COMMIT_OID, "tree": {"sha": _TREE_OID}},
            )
        if "/git/ref/heads/repoguard/repairs/" in target:
            if self.branch_oid is None:
                return _json_response(404, {"message": "not found"})
            return _json_response(200, self._branch())
        if request.method.value == "POST" and target.endswith("/git/refs"):
            assert body == {"ref": _BRANCH_REF, "sha": _COMMIT_OID}
            if self.branch_oid is not None:
                return _json_response(422, {"message": "exists"})
            self.branch_oid = _COMMIT_OID
            if self.ambiguous_branch:
                self.ambiguous_branch = False
                raise TimeoutError
            return _json_response(201, self._branch())
        if "/pulls?state=all" in target:
            values = [] if self.replacement is None else [self.replacement]
            return _json_response(200, values)
        if request.method.value == "POST" and target.endswith("/pulls"):
            if self.fail_pull_request:
                return _json_response(500, {"message": "unavailable"})
            self.replacement = self._replacement_pull_request(body)
            if self.ambiguous_pull_request:
                self.ambiguous_pull_request = False
                raise TimeoutError
            return _json_response(201, self.replacement)
        if target == "/repos/owner/repository/pulls/8":
            assert self.replacement is not None
            return _json_response(200, self.replacement)
        raise AssertionError(f"unexpected request: {request.method.value} {target}")

    def _source_pull_request(self) -> dict[str, object]:
        repository = {"id": _REPOSITORY_ID, "full_name": _REPOSITORY_FULL_NAME}
        return {
            "id": 700,
            "number": 7,
            "state": self.source_state,
            "base": {"ref": "main", "sha": _BASE_OID, "repo": repository},
            "head": {"ref": "feature", "sha": self.source_head_oid, "repo": repository},
        }

    def _check_run(
        self,
        *,
        external_id: str,
        status: str,
        conclusion: str | None,
        summary: str,
    ) -> dict[str, object]:
        return {
            "id": 17,
            "node_id": "CR_node",
            "name": "RepoGuard review",
            "head_sha": _HEAD_OID,
            "external_id": external_id,
            "status": status,
            "conclusion": conclusion,
            "html_url": "https://github.com/owner/repository/runs/17",
            "output": {
                "title": "RepoGuard review",
                "summary": summary,
                "annotations_count": len(self.check_annotations),
            },
        }

    def _branch(self) -> dict[str, object]:
        assert self.branch_oid is not None
        return {
            "ref": _BRANCH_REF,
            "object": {"type": "commit", "sha": self.branch_oid},
        }

    def _replacement_pull_request(self, body: dict[str, object]) -> dict[str, object]:
        repository = {"id": _REPOSITORY_ID, "full_name": _REPOSITORY_FULL_NAME}
        return {
            "id": 800,
            "number": 8,
            "node_id": "PR_node",
            "html_url": "https://github.com/owner/repository/pull/8",
            "draft": body["draft"],
            "state": "open",
            "title": body["title"],
            "body": body["body"],
            "base": {"ref": body["base"], "repo": repository},
            "head": {"ref": body["head"], "repo": repository},
        }


class _FakeRepairSession:
    def __init__(self) -> None:
        self.current, _ = _validated_repair()
        self.approve_calls = 0
        self.apply_calls = 0
        self.entry = RepairPublicationEntry(
            1,
            "src/app.py",
            "100644",
            _BLOB_OID,
            len(_BLOB_CONTENT),
        )

    def snapshot(self) -> RepairSnapshot:
        return self.current

    def approve(
        self,
        *,
        subject: str,
        expected_candidate_id: str,
        expected_validation_sha256: str,
        confirmation: str,
    ) -> RepairSnapshot:
        assert expected_candidate_id == _CANDIDATE_ID
        assert expected_validation_sha256 == _VALIDATION_SHA256
        assert confirmation == REPAIR_APPROVAL_CONFIRMATION
        self.approve_calls += 1
        approval = RepairApproval(
            1,
            _LOCAL_APPROVAL_SHA256,
            _CANDIDATE_ID,
            _VALIDATION_SHA256,
            subject,
            confirmation,
            3,
        )
        self.current = replace(
            self.current,
            state=RepairState.APPROVED,
            updated_at_us=3,
            approval=approval,
        )
        return self.current

    def apply(self, *, expected_approval_sha256: str) -> RepairSnapshot:
        assert expected_approval_sha256 == _LOCAL_APPROVAL_SHA256
        self.apply_calls += 1
        application = RepairApplication(
            1,
            _APPLICATION_SHA256,
            _LOCAL_APPROVAL_SHA256,
            f"refs/repoguard/repairs/{_CANDIDATE_ID}",
            _COMMIT_OID,
            4,
        )
        self.current = replace(
            self.current,
            state=RepairState.APPLIED,
            updated_at_us=4,
            application=application,
        )
        return self.current

    def publication_manifest(
        self,
        *,
        expected_application_sha256: str,
    ) -> RepairPublicationManifest:
        assert expected_application_sha256 == _APPLICATION_SHA256
        return RepairPublicationManifest(
            1,
            "a" * 64,
            _SESSION_ID,
            _APPLICATION_SHA256,
            _LOCAL_APPROVAL_SHA256,
            _CANDIDATE_ID,
            "sha1",
            f"refs/repoguard/repairs/{_CANDIDATE_ID}",
            _HEAD_OID,
            _TREE_OID,
            _COMMIT_OID,
            (self.entry,),
            len(_BLOB_CONTENT),
        )

    def publication_blob(
        self,
        *,
        manifest: RepairPublicationManifest,
        entry: RepairPublicationEntry,
    ) -> RepairPublicationBlob:
        assert entry == self.entry
        return RepairPublicationBlob(1, manifest.manifest_sha256, entry, _BLOB_CONTENT)


class _FakeRepairManager:
    def __init__(self, session: _FakeRepairSession) -> None:
        self.session = session

    def open_session(self, session_id: str) -> _FakeRepairSession:
        assert session_id == _SESSION_ID
        return self.session


def _service(
    root: Path,
    fake: _FakeGitHub,
    *,
    repair: _FakeRepairSession | None = None,
    now: int = 2_000_000,
    interface: GitHubApprovalInterface = GitHubApprovalInterface.CLI,
    expected_principal_login: str | None = None,
) -> tuple[GitHubPublicationService, GitHubPublicationStore]:
    store = _store(root)
    transport = GitHubTransport("github_pat_EXPLICIT", sender=fake)
    manager = None if repair is None else _FakeRepairManager(repair)
    service = GitHubPublicationService(
        transport=transport,
        store=store,
        interface=interface,
        repair_manager=manager,
        clock=lambda: now,
        expected_principal_login=expected_principal_login,
    )
    return service, store


def test_expected_action_principal_must_match_token_for_new_and_final_publication(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    mismatched, store = _service(
        state_root,
        fake,
        interface=GitHubApprovalInterface.ACTION,
        expected_principal_login="workflow-actor",
    )
    proposal = _check_proposal()
    store.record_proposal(proposal)

    with pytest.raises(GitHubPublicationError) as rejected:
        mismatched.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )

    assert rejected.value.code == GitHubPublicationErrorCode.PRINCIPAL_MISMATCH.value
    assert rejected.value.stage is GitHubPublicationStage.PRINCIPAL
    assert fake.write_requests == []

    matched, _ = _service(
        state_root,
        fake,
        interface=GitHubApprovalInterface.ACTION,
        expected_principal_login="reviewer",
    )
    result = matched.publish_check(
        proposal.proposal_sha256,
        confirmation=GITHUB_CHECK_CONFIRMATION,
    )
    assert result.state is GitHubPublicationState.CHECK_PUBLISHED
    write_count = len(fake.write_requests)

    revalidation_mismatch, _ = _service(
        state_root,
        fake,
        interface=GitHubApprovalInterface.ACTION,
        expected_principal_login="workflow-actor",
    )
    with pytest.raises(GitHubPublicationError) as revalidation:
        revalidation_mismatch.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )
    assert revalidation.value.code == GitHubPublicationErrorCode.PRINCIPAL_MISMATCH.value
    assert len(fake.write_requests) == write_count


def test_source_pull_request_is_strict_and_forks_are_read_only(state_root: Path) -> None:
    fake = _FakeGitHub()
    service, _ = _service(state_root, fake)

    source = service.read_source_pull_request(
        repository_id=_REPOSITORY_ID,
        repository_full_name=_REPOSITORY_FULL_NAME,
        pull_request_number=7,
    )

    assert source.base_ref == "main"
    assert source.base_oid == _BASE_OID
    assert source.head_oid == _HEAD_OID
    assert source.writable is True
    fake.repository_is_fork = True
    with pytest.raises(GitHubPublicationError) as raised:
        service.read_source_pull_request(
            repository_id=_REPOSITORY_ID,
            repository_full_name=_REPOSITORY_FULL_NAME,
            pull_request_number=7,
            require_same_repository=True,
        )
    assert raised.value.code == GitHubPublicationErrorCode.FORK_UNSUPPORTED.value
    assert fake.write_requests == []


@pytest.mark.parametrize("ambiguous", ["create", "append", "final"])
def test_check_batches_annotations_and_resolves_ambiguous_write_by_readback(
    state_root: Path,
    ambiguous: str,
) -> None:
    fake = _FakeGitHub()
    fake.ambiguous_check_create = ambiguous == "create"
    fake.ambiguous_check_append = ambiguous == "append"
    fake.ambiguous_check_final = ambiguous == "final"
    service, store = _service(state_root, fake)
    proposal = _check_proposal(annotations=51)
    store.record_proposal(proposal)

    result = service.publish_check(
        proposal.proposal_sha256,
        confirmation=GITHUB_CHECK_CONFIRMATION,
    )

    assert result.state is GitHubPublicationState.CHECK_PUBLISHED
    assert len(fake.check_annotations) == 51
    annotation_writes = [
        cast(dict[str, object], json.loads(item.body or b"{}"))
        for item in fake.write_requests
        if item.target.endswith("/check-runs") or item.target.endswith("/check-runs/17")
    ]
    batch_sizes = [
        len(
            cast(
                list[object],
                cast(dict[str, object], body["output"]).get("annotations", []),
            )
        )
        for body in annotation_writes
    ]
    assert batch_sizes == [50, 1, 0]
    write_count = len(fake.write_requests)
    fake.source_state = "closed"
    assert (
        service.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )
        == result
    )
    assert len(fake.write_requests) == write_count


def test_permission_and_stale_head_fail_before_any_github_write(state_root: Path) -> None:
    for mismatch in ("permission", "head"):
        fake = _FakeGitHub()
        if mismatch == "permission":
            fake.permission = "read"
        else:
            fake.source_head_oid = "f" * 40
        (state_root / mismatch).mkdir(mode=0o700)
        service, store = _service(state_root / mismatch, fake)
        proposal = _check_proposal()
        store.record_proposal(proposal)

        with pytest.raises(GitHubPublicationError) as raised:
            service.publish_check(
                proposal.proposal_sha256,
                confirmation=GITHUB_CHECK_CONFIRMATION,
            )

        expected = (
            GitHubPublicationErrorCode.PERMISSION_DENIED
            if mismatch == "permission"
            else GitHubPublicationErrorCode.PULL_REQUEST_STALE
        )
        assert raised.value.code == expected.value
        assert fake.write_requests == []
        assert store.status(proposal.proposal_sha256).approval is None


def test_transport_error_preserves_stable_code_without_secret(
    state_root: Path,
) -> None:
    class _Unauthorized(_FakeGitHub):
        def send(self, request: GitHubWireRequest) -> GitHubWireResponse:
            if request.target == "/user":
                return _json_response(401, {"token": "LEAK_ME"})
            return super().send(request)

    fake = _Unauthorized()
    service, store = _service(state_root, fake)
    proposal = _check_proposal()
    store.record_proposal(proposal)

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )

    error = raised.value
    assert error.domain is GitHubPublicationErrorDomain.TRANSPORT
    assert error.code == "authentication_failed"
    assert error.stage is GitHubPublicationStage.PRINCIPAL
    assert "LEAK_ME" not in str(error)
    assert "github_pat_EXPLICIT" not in repr(error)


@pytest.mark.parametrize(
    ("status", "code", "retryable"),
    [
        (401, "authentication_failed", False),
        (403, "forbidden", False),
        (404, "not_found", False),
        (409, "conflict", False),
        (422, "validation_failed", False),
        (429, "rate_limited", True),
        (500, "server_error", True),
        (302, "redirect_forbidden", False),
        (418, "unexpected_status", False),
    ],
)
def test_service_preserves_all_github_http_error_classes(
    state_root: Path,
    status: int,
    code: str,
    retryable: bool,
) -> None:
    class _HTTPFailure(_FakeGitHub):
        def send(self, request: GitHubWireRequest) -> GitHubWireResponse:
            if request.target == "/user":
                return _json_response(status, {"message": "private response"})
            return super().send(request)

    fake = _HTTPFailure()
    service, store = _service(state_root, fake)
    proposal = _check_proposal()
    store.record_proposal(proposal)

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )

    assert raised.value.domain is GitHubPublicationErrorDomain.TRANSPORT
    assert raised.value.code == code
    assert raised.value.retryable is retryable
    assert raised.value.ambiguous is False
    assert fake.write_requests == []


def test_confirmation_kind_and_expiry_fail_without_github_write(state_root: Path) -> None:
    check_fake = _FakeGitHub()
    (state_root / "check").mkdir(mode=0o700)
    check_service, check_store = _service(state_root / "check", check_fake)
    check = _check_proposal()
    check_store.record_proposal(check)
    with pytest.raises(GitHubPublicationError) as wrong_confirmation:
        check_service.publish_check(
            check.proposal_sha256,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
        )
    assert wrong_confirmation.value.code == GitHubPublicationErrorCode.APPROVAL_MISMATCH.value
    assert check_fake.requests == []

    repair_fake = _FakeGitHub()
    repair_session = _FakeRepairSession()
    (state_root / "repair").mkdir(mode=0o700)
    repair_service, repair_store = _service(
        state_root / "repair",
        repair_fake,
        repair=repair_session,
    )
    repair = _repair_proposal()
    repair_store.record_proposal(repair, session_id=_SESSION_ID)
    with pytest.raises(GitHubPublicationError) as wrong_kind:
        repair_service.publish_check(
            repair.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )
    assert wrong_kind.value.code == GitHubPublicationErrorCode.KIND_MISMATCH.value
    assert repair_fake.requests == []

    expired_fake = _FakeGitHub()
    (state_root / "expired").mkdir(mode=0o700)
    expired_service, expired_store = _service(
        state_root / "expired",
        expired_fake,
        now=86_401_000_000,
    )
    expired_store.record_proposal(check)
    with pytest.raises(GitHubPublicationError) as expired:
        expired_service.publish_check(
            check.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )
    assert expired.value.code == GitHubPublicationErrorCode.PROPOSAL_EXPIRED.value
    assert expired_fake.write_requests == []
    assert expired_store.status(check.proposal_sha256).approval is None


def test_idempotent_final_result_still_requires_same_token_principal(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    service, store = _service(state_root, fake)
    proposal = _check_proposal()
    store.record_proposal(proposal)
    service.publish_check(
        proposal.proposal_sha256,
        confirmation=GITHUB_CHECK_CONFIRMATION,
    )
    write_count = len(fake.write_requests)
    fake.actor_id = 43
    fake.actor_login = "intruder"

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_check(
            proposal.proposal_sha256,
            confirmation=GITHUB_CHECK_CONFIRMATION,
        )

    assert raised.value.code == GitHubPublicationErrorCode.APPROVAL_MISMATCH.value
    assert len(fake.write_requests) == write_count


def test_repair_publishes_exact_objects_branch_and_draft_pr(state_root: Path) -> None:
    fake = _FakeGitHub()
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)

    result = service.publish_repair(
        proposal.proposal_sha256,
        confirmation=GITHUB_REPAIR_CONFIRMATION,
    )

    assert result.state is GitHubPublicationState.REPAIR_PUBLISHED
    assert result.application_sha256 == _APPLICATION_SHA256
    assert fake.blobs == {_BLOB_OID}
    assert fake.tree_exists and fake.commit_exists
    assert fake.branch_oid == _COMMIT_OID
    assert fake.replacement is not None
    assert fake.replacement["draft"] is True
    assert fake.replacement["title"] == _PR_TITLE
    assert fake.replacement["body"] == _PR_BODY
    assert repair.approve_calls == repair.apply_calls == 1
    status = store.status(proposal.proposal_sha256)
    assert status.partial_result is not None
    assert status.result == result
    write_count = len(fake.write_requests)
    fake.source_state = "closed"
    assert (
        service.publish_repair(
            proposal.proposal_sha256,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
        )
        == result
    )
    assert service.recover(proposal.proposal_sha256) == result
    assert len(fake.write_requests) == write_count
    assert repair.approve_calls == repair.apply_calls == 1


def test_repair_resolves_every_ambiguous_write_by_exact_readback(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    fake.ambiguous_blob = True
    fake.ambiguous_tree = True
    fake.ambiguous_commit = True
    fake.ambiguous_branch = True
    fake.ambiguous_pull_request = True
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)

    result = service.publish_repair(
        proposal.proposal_sha256,
        confirmation=GITHUB_REPAIR_CONFIRMATION,
    )

    assert result.state is GitHubPublicationState.REPAIR_PUBLISHED
    targets = [item.target for item in fake.write_requests]
    assert targets.count("/repos/owner/repository/git/blobs") == 1
    assert targets.count("/repos/owner/repository/git/trees") == 1
    assert targets.count("/repos/owner/repository/git/commits") == 1
    assert targets.count("/repos/owner/repository/git/refs") == 1
    assert targets.count("/repos/owner/repository/pulls") == 1


def test_repair_partial_recovery_uses_same_approval_and_does_not_reapply(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    fake.fail_pull_request = True
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_repair(
            proposal.proposal_sha256,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
        )

    assert raised.value.code == GitHubPublicationErrorCode.AMBIGUOUS_WRITE.value
    partial = store.status(proposal.proposal_sha256)
    assert partial.partial_result is not None
    assert partial.result is None
    approval = partial.approval
    fake.fail_pull_request = False

    result = service.recover_repair(proposal.proposal_sha256)

    assert result.state is GitHubPublicationState.REPAIR_PUBLISHED
    assert result.approval == approval
    assert repair.approve_calls == repair.apply_calls == 1


def test_foreign_branch_is_never_overwritten_or_deleted(state_root: Path) -> None:
    fake = _FakeGitHub()
    fake.branch_oid = "f" * 40
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_repair(
            proposal.proposal_sha256,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
        )

    assert raised.value.code == GitHubPublicationErrorCode.REMOTE_CONFLICT.value
    assert raised.value.stage is GitHubPublicationStage.BRANCH
    assert fake.branch_oid == "f" * 40
    assert fake.replacement is None
    assert all(item.method.value != "PATCH" for item in fake.requests)


def test_closed_or_foreign_replacement_pr_stops_and_keeps_authorized_branch(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)
    fake.replacement = fake._replacement_pull_request(
        {
            "title": _PR_TITLE,
            "head": _BRANCH,
            "base": "main",
            "body": _PR_BODY,
            "draft": True,
        }
    )
    fake.replacement["state"] = "closed"

    with pytest.raises(GitHubPublicationError) as raised:
        service.publish_repair(
            proposal.proposal_sha256,
            confirmation=GITHUB_REPAIR_CONFIRMATION,
        )

    assert raised.value.code == GitHubPublicationErrorCode.REMOTE_CONFLICT.value
    assert raised.value.stage is GitHubPublicationStage.PULL_REQUEST
    assert fake.branch_oid == _COMMIT_OID
    status = store.status(proposal.proposal_sha256)
    assert status.partial_result is not None
    assert status.result is None


def test_final_repair_revalidation_fails_closed_for_pr_branch_objects_and_permission(
    state_root: Path,
) -> None:
    fake = _FakeGitHub()
    repair = _FakeRepairSession()
    service, store = _service(state_root, fake, repair=repair)
    proposal = _repair_proposal()
    store.record_proposal(proposal, session_id=_SESSION_ID)
    service.publish_repair(
        proposal.proposal_sha256,
        confirmation=GITHUB_REPAIR_CONFIRMATION,
    )
    write_count = len(fake.write_requests)

    fake.actor_id = 43
    fake.actor_login = "intruder"
    with pytest.raises(GitHubPublicationError) as actor:
        service.recover(proposal.proposal_sha256)
    assert actor.value.code == GitHubPublicationErrorCode.APPROVAL_MISMATCH.value
    fake.actor_id = 42
    fake.actor_login = "reviewer"

    fake.permission = "read"
    with pytest.raises(GitHubPublicationError) as permission:
        service.recover(proposal.proposal_sha256)
    assert permission.value.code == GitHubPublicationErrorCode.PERMISSION_DENIED.value
    fake.permission = "write"

    fake.blobs.clear()
    with pytest.raises(GitHubPublicationError) as blob:
        service.recover(proposal.proposal_sha256)
    assert blob.value.stage is GitHubPublicationStage.OBJECTS
    fake.blobs.add(_BLOB_OID)

    fake.tree_exists = False
    with pytest.raises(GitHubPublicationError) as tree:
        service.recover(proposal.proposal_sha256)
    assert tree.value.stage is GitHubPublicationStage.OBJECTS
    fake.tree_exists = True

    fake.commit_exists = False
    with pytest.raises(GitHubPublicationError) as commit:
        service.recover(proposal.proposal_sha256)
    assert commit.value.stage is GitHubPublicationStage.OBJECTS
    fake.commit_exists = True

    fake.branch_oid = "f" * 40
    with pytest.raises(GitHubPublicationError) as branch:
        service.recover(proposal.proposal_sha256)
    assert branch.value.stage is GitHubPublicationStage.BRANCH
    fake.branch_oid = _COMMIT_OID

    assert fake.replacement is not None
    fake.replacement["state"] = "closed"
    with pytest.raises(GitHubPublicationError) as pull_request:
        service.recover(proposal.proposal_sha256)
    assert pull_request.value.stage is GitHubPublicationStage.PULL_REQUEST
    assert len(fake.write_requests) == write_count
